accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout

from . import views

urlpatterns = [
    url(r'^send_login_email$', views.send_login_email, name='send_login_email'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', logout, {'next_page': '/'}, name='logout'),
]

lists/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^new$', views.new_list, name='new_list'),
    url(r'^(\d+)/$', views.view_list, name='view_list'),
    url(r'^users/(.+)/$', views.my_lists, name='my_lists'),
    url(r'^(\d+)/share$', views.list_share, name='list_share'),
]

superlists/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from lists.views import home_page
from lists import urls as list_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home_page, name='home'),
    url(r'^lists/', include(list_urls)),
]

accounts/models.py
import uuid

from django.db import models
from django.contrib import auth

# Fix for
# ValueError: The following fields do not exist in this model or are m2m fields: last_login
auth.signals.user_logged_in.disconnect(auth.models.update_last_login)


class User(models.Model):
    email = models.EmailField(primary_key=True)
    REQUIRED_FIELDS = []
    USERNAME_FIELD = 'email'
    is_anonymous = False
    is_authenticated = True

    def __str__(self):
        return self.email

class Token(models.Model):
    email = models.EmailField()
    uid = models.CharField(default=uuid.uuid4,
                           max_length=40)

lists/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings


class List(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                              blank=True, null=True)
    shared_with = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='shared_lists')

    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])

    @staticmethod
    def create_new(first_item_text, owner=None):
        list_ = List.objects.create(owner=owner)
        Item.objects.create(text=first_item_text, list=list_)
        return list_

    @property
    def name(self):
        return self.item_set.first().text

    def __str__(self):
        return self.name


class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None)

    class Meta:
        ordering = ('id',)
        unique_together = ('list', 'text')

    def __str__(self):
        return self.text

lists/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from .models import Item, List

EMPTY_ITEM_ERROR = "You can't have an empty list item"


class ItemForm(forms.models.ModelForm):

    class Meta:
        model = Item
        fields = ['text']
        widgets = {
            'text': forms.fields.TextInput(attrs={
                'placeholder': 'Enter a to-do item',
                'class': 'form-control-lg',
            })
        }
        error_messages = {
            'text': {'required': EMPTY_ITEM_ERROR}
        }


DUPLICATE_ITEM_ERROR = "You've already got this in your list"


class ExistingListItemForm(ItemForm):

    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text': [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)


class NewListForm(ItemForm):
    def save(self, owner):
        if owner.is_authenticated:
            return List.create_new(
                first_item_text=self.cleaned_data['text'],
                owner=owner)
        else:
            return List.create_new(
                first_item_text=self.cleaned_data['text'])

accounts/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpRequest
from django.core.mail import send_mail
from django.contrib import messages
from django.contrib import auth

from .models import Token, User

SUBJECT = 'Your login link for Superlists'
BODY = 'Use this link to log in:\n\n'
FROM_EMAIL = 'noreply@superlists'
MESSAGE = "Check your email, we've sent you a link you can use to log in."


def send_login_email(request: HttpRequest):
    email = request.POST['email']
    token = Token.objects.create(email=email)
    url = request.build_absolute_uri(
        f"{reverse('login')}?token={token.uid}"
    )
    message_body = f'{BODY}{url}'
    send_mail(
        SUBJECT,
        message_body,
        FROM_EMAIL,
        [email],
    )
    messages.success(request, MESSAGE)
    return redirect('/')


def login(request: HttpRequest):
    token = request.GET.get('token')
    user = auth.authenticate(uid=token)
    if user:
        auth.login(request, user)
    return redirect('/')

lists/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model
from django.contrib import messages

from .models import Item, List
from .forms import ItemForm, ExistingListItemForm, NewListForm

User = get_user_model()


def home_page(request: HttpRequest):
    return render(request, 'home.html', {'form': ItemForm()})


def view_list(request: HttpRequest, list_id):
    list_ = List.objects.get(id=list_id)
    form = None
    if request.method == 'POST':
        form = ExistingListItemForm(for_list=list_, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(list_)
    else:
        form = ExistingListItemForm(for_list=list_)

    return render(request, 'list.html',
                  {'list': list_, 'form': form, })


def new_list(request: HttpRequest):
    form = NewListForm(data=request.POST)
    if form.is_valid():
        list_ = form.save(owner=request.user)
        return redirect(list_)
    return render(request, 'home.html', {'form': form})


def my_lists(request: HttpRequest, email):
    owner = User.objects.get(email=email)
    return render(request, 'my_lists.html', {'owner': owner})


def list_share(request: HttpRequest, list_id):
    email = request.POST['shared_email']
    list_ = List.objects.get(id=list_id)
    list_.shared_with.add(email)

    messages.success(request, f'List shared with {email}')
    return redirect(list_)

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible"
          content="IE=edge">
    <meta name="viewport"
          content="width=device-width, initial-scale=1">
    <title>To-Do lists</title>
    <link href="/static/bootstrap/css/bootstrap.min.css"
          rel="stylesheet">
    <link href="/static/base.css"
          rel="stylesheet">
    <link rel="icon"
          type="image/png"
          href="/static/img/favicon-32x32.png"
          sizes="32x32" />
    <link rel="icon"
          type="image/png"
          href="/static/img/favicon-16x16.png"
          sizes="16x16" />
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between">
        <a class="navbar-brand"
           href="#">SuperLists</a>
        {% if user.email %}
        <ul class="navbar-nav">
            <a href="{% url 'my_lists' user.email %}"
               class="nav-item nav-link">My lists</a>
        </ul>
        <ul class="navbar-nav">
            <a href="#"
               class="nav-item nav-link">My lists</a>
            <li class="nav-item navbar-text">Logged in as {{ user.email }}</li>
            <a class="nav-item nav-link"
               href="{% url 'logout' %}">Log out</a>
        </ul>
        {% else %}
        <form class="form-inline my-2 my-lg-0"
              method="POST"
              action="{% url 'send_login_email' %}">
            {% csrf_token %}
            <label class="navbar-text" for="name">Enter email to log in:</label>
            <input class="form-control mx-sm-2"
                   name="email"
                   id="name"
                   type="email"
                   placeholder="E-mail">
            <button class="btn btn-outline-success my-2 my-sm-0"
                    type="submit">Submit</button>
        </form>
        {% endif %}
    </nav>

    {% if messages %}
    <div class="row">
        <div class="col-md-8 text-center">
            {% for message in messages %} {% if message.level_tag == 'success' %}
            <div class="alert alert-success">{{ message }}</div>
            {% else %}
            <div class="alert alert-warning">{{ message }}</div>
            {% endif %} {% endfor %}
        </div>
    </div>
    {% endif %}


    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3 jumbotron">
                <div class="text-center">
                    <h1>{% block header_text %}{% endblock %}</h1>
                    {% block list_form %}
                    <form method="POST"
                          action="{% block form_action %}{% endblock %}">
                        {% csrf_token %} {{ form.text }} {% if form.errors %}
                        <div class="form-control is-invalid">
                            <span class="help-block">{{ form.text.errors }}</span>
                        </div>
                        {% endif %}
                    </form>
                    {% endblock list_form %}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 offset-md-3">
                {% block table %} {% endblock %}
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 offset-md-3">
                {% block extra_content %} {% endblock %}
            </div>
        </div>

    </div>

    <script src="/static/js/jquery-3.2.1.min.js"></script>
    <script src="/static/js/list.js"></script>
    <script>
        $(() => {
            window.SuperLists.initialize();
        });
    </script>
    </script>

</body>

</html>

lists/templates/home.html
{% extends 'base.html' %}
{% block header_text %}Start a new To-Do list{% endblock %}
{% block form_action %}{% url 'new_list' %}{%endblock %}

lists/templates/list.html
{% extends 'base.html' %} {% block header_text %}Your To-Do list{% endblock header_text %}
{% block extra_content %}
<div class="container">
    {% if list.owner %}
        <span id="id_list_owner">{{ list.owner }}</span>
    {% else %}
    {% endif %}
    <ul class="row list-group"
        id="list-share">
        {% for email in list.shared_with.all %}
            <li class="list-group-item">{{ email }}</li>
        {% endfor %}    
    </ul>
    <form class="row"
          action="{% url 'list_share' list.id %}"
          method="post">
        {% csrf_token %}
        <label for="shared_email">Share this list with:</label>
        <input type="email"
        name="shared_email"
        id="shared_email"
        class="form-control mx-sm-2"
        placeholder="your-friend@example.com">
    </form>
</div>
{% endblock extra_content %}
{% block form_action %}{% url 'view_list' list.id %}{%endblock form_action %}
{% block table %}
<table id="id_list_table"
       class="table">
    {% for item in list.item_set.all %}
    <tr>
        <td>{{ forloop.counter }}: {{ item.text }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock table %}

lists/templates/my_lists.html
{% extends 'base.html' %}
{% block header_text %}My Lists{% endblock %}
{% block list_form %}{% endblock list_form %}
{% block extra_content %}
    <h2>{{ owner }}'s lists</h2>
    <ul class="list-group">
        {% for list in owner.list_set.all %}
            <li class="list-group-item">
                <a href="{{ list.get_absolute_url }}">
                    {{ list.name }}
                </a>
            </li>
        {% endfor %}
    </ul>
    <h2>List's shared by other users</h2>
    <ul class="list-group">
        {% for list in owner.shared_lists.all %}
            <li class="list-group-item">
                <a  class="list-item-group"
                    href="{{  list.get_absolute_url }}">
                    {{ list.name }}
                </a>
                list.owner
            </li>
        {% endfor %}
    </ul>
{% endblock extra_content %}